Repository waffle-card/client, pull requests merged in 2022-02, with the labels that each got.

#1 feat: WC-20 / 패키지 버전 업그레이드
  package.json
  yarn.lock
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#2 refactor: WC-14/ 새로운 API 모듈 구현
  .env
  src/apis/auth.js
  src/apis/comment.js
  src/apis/index.jsx
  src/apis/like.js
  src/apis/request.js
  src/apis/waffleCard.js
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#3 refactor: [WC-22] 회원가입 api 교체
  src/pages/SignUpPage/index.jsx
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#4 refacotr: WC-34/ 로그인 구조 변경 및 api 연동, 유저 전역 상태관리 리팩토링
  src/apis/request.js
  src/contexts/UserProvider.jsx
  src/pages/LoginPage/index.jsx
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#5 refactor: WC-16/CardEditModal 순수한 컴포넌트로 리팩토링
  src/components/index.js
  src/components/molecule/ColorPalette/ColorPalette.jsx
  src/components/molecule/LikeBox/LikeBox.jsx
  src/components/molecule/LikeBox/LikeBox.stories.jsx
  src/components/molecule/ToggleBox/ToggleBox.jsx
  src/components/molecule/ToggleBox/ToggleBox.stories.jsx
  src/components/organism/CardEditModal/CardEditModal.jsx
  src/components/organism/CardEditModal/CardEditModal.stories.jsx
  src/components/organism/CardsContainer/CardsContainer.jsx
  src/components/organism/ChattingCard/Header.jsx
  src/components/organism/WaffleCard/Basic.jsx
  src/components/organism/WaffleCard/Edit.jsx
  src/components/organism/WaffleCard/Plain.jsx
  src/components/organism/WaffleCard/WaffleCard.jsx
  src/pages/HomePage/index.jsx
  src/utils/index.jsx
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#6 refactor: [wc-21] route 관련 리팩토링 및 v6 적용
  package.json
  src/App.jsx
  src/components/atom/BackButton/BackButton.jsx
  src/components/molecule/Card/Empty.jsx
  src/components/molecule/Tab/TabItem.jsx
  src/components/organism/CardsContainer/CardsContainer.jsx
  src/components/organism/ChattingCard/ChattingCard.jsx
  src/components/organism/ChattingCard/Header.jsx
  src/components/organism/Header/Header.jsx
  src/components/organism/NameChangeModal/NameChangeModal.jsx
  src/components/organism/PasswordChangeModal/PasswordChangeModal.jsx
  src/pages/HomePage/index.jsx
  src/pages/LoginPage/index.jsx
  src/pages/MyPage/index.jsx
  src/pages/SignUpPage/index.jsx
  src/pages/index.jsx
  src/routes/PrivateRoute.jsx
  src/routes/PublicRoute.jsx
  src/routes/Router.jsx
  yarn.lock
Labels: 🛠 Refactor, 🐢 리뷰 요청

#7 [WC-17] refactor: 채팅카드모달 리팩토링
  package.json
  src/components/molecule/EditBox/EditBox.jsx
  src/components/molecule/LikeBox/LikeBox.jsx
  src/components/molecule/Modal/Modal.jsx
  src/components/organism/ChattingCard/Bookmark.jsx
  src/components/organism/ChattingCard/ChattingCard.jsx
  src/components/organism/ChattingCard/ChattingCard.stories.jsx
  src/components/organism/ChattingCard/Comment.jsx
  src/components/organism/ChattingCard/CommentEditor.jsx
  src/components/organism/ChattingCard/CommentList.jsx
  src/components/organism/ChattingCard/Header.jsx
  src/components/organism/ChattingCard/Like.jsx
  src/components/organism/ChattingCard/Message.jsx
  src/styles/common.jsx
  src/styles/global-styles.jsx
  yarn.lock
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#8 [WC-23] refactor: MyPage리팩토링 및 api재연결
  src/components/molecule/Tab/TabItem.jsx
  src/components/organism/Header/Header.jsx
  src/components/organism/NameChangeModal/NameChangeModal.jsx
  src/components/organism/NameChangeModal/NameChangeModal.stories.jsx
  src/components/organism/PasswordChangeModal/PasswordChangeModal.jsx
  src/components/organism/PasswordChangeModal/PasswordChangeModal.stories.js
  src/pages/LoginPage/index.jsx
  src/pages/MyPage/index.jsx
  src/routes/PrivateRoute.jsx
  src/routes/PublicRoute.jsx
  src/routes/Router.jsx
Labels: 🛠 Refactor, 🐢 리뷰 요청

#9 [WC-25] refactor: HomePage에서 Tab관련 로직 정리
  src/components/molecule/Tab/Tab.jsx
  src/components/molecule/Tab/TabItem.jsx
  src/pages/HomePage/index.jsx
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#10 [WC-38] refactor: Tab컴포넌트 리팩토링 및 상수, mixin 생성 후 적용
  .storybook/main.js
  craco.config.js
  src/components/molecule/Tab/Tab.jsx
  src/components/molecule/Tab/Tab.stories.jsx
  src/components/molecule/Tab/TabItem.jsx
  src/constants/index.js
  src/pages/HomePage/index.jsx
  src/styles/mixin.js
Labels: 🛠 Refactor, 🐢 리뷰 요청

#11 [WC-39] refactor: ScrollGuide컴포넌트 리팩토링 및 Tab관련 코드 수정
  src/components/molecule/ScrollGuide/ScrollGuide.jsx
  src/components/molecule/ScrollGuide/ScrollGuide.stories.jsx
  src/components/molecule/Tab/Tab.jsx
  src/components/molecule/Tab/TabItem.jsx
  src/constants/index.js
  src/pages/HomePage/index.jsx
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#12 [WC-35] refactor: 홈페이지 리팩토링
  src/App.jsx
  src/apis/comment.js
  src/apis/like.js
  src/apis/request.js
  src/apis/waffleCard.js
  src/components/index.js
  src/components/molecule/Card/Empty.jsx
  src/components/molecule/Modal/Modal.jsx
  src/components/organism/CardEditModal/CardEditModal.jsx
  src/components/organism/CardEditModal/HashTagInput.jsx
  src/components/organism/CardEditModal/HashTagsInputs.jsx
  src/components/organism/CardsContainer/CardsContainer.jsx
  src/components/organism/CardsContainer/CardsContainer.stories.jsx
  src/components/organism/CardsContainer/LoginGuide.jsx
  src/components/organism/CardsContainer/NoCardGuide.jsx
  src/components/organism/ChattingCard/ChattingCard.jsx
  src/components/organism/ChattingCard/Comment.jsx
  src/components/organism/ChattingCard/Header.jsx
  src/components/organism/Modals/Modals.jsx
  src/components/organism/WaffleCard/Basic.jsx
  src/components/organism/WaffleCard/Edit.jsx
  src/components/organism/WaffleCard/Plain.jsx
  src/components/organism/WaffleCard/WaffleCard.jsx
  src/components/organism/WaffleCard/WaffleCard.stories.jsx
  src/contexts/index.jsx
  src/contexts/modals/ModalsProvider.jsx
  src/contexts/user/UserProvider.jsx
  src/hooks/index.jsx
  src/hooks/useModals.jsx
  src/pages/HomePage/index.jsx
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#13 WC-41 fix: HomePage 버그 수정
  src/apis/like.js
  src/components/molecule/LikeBox/LikeBox.jsx
  src/components/organism/CardsContainer/CardsContainer.jsx
  src/components/organism/ChattingCard/ChattingCard.jsx
  src/components/organism/ChattingCard/CommentEditor.jsx
  src/components/organism/ChattingCard/CommentList.jsx
  src/components/organism/ChattingCard/Header.jsx
  src/components/organism/WaffleCard/WaffleCard.jsx
  src/contexts/user/UserProvider.jsx
  src/pages/HomePage/index.jsx
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#14 [WC-43] refactor: 사용하지 않는 코드 제거 및 컴포넌트 일부 네이밍 변경
  src/apis/index.jsx
  src/apis/request.js
  src/components/index.js
  src/components/molecule/ColorPalette/ColorPalette.stories.jsx
  src/components/molecule/ColorPicker/ColorItem.jsx
  src/components/molecule/ColorPicker/ColorPicker.jsx
  src/components/molecule/ColorPicker/ColorPicker.stories.jsx
  src/components/molecule/LikeToggle/LikeToggle.jsx
  src/components/molecule/LikeToggle/LikeToggle.stories.jsx
  src/components/organism/CardEditModal/CardEditModal.jsx
  src/components/organism/CardEditModal/EmojiPickerActiveButton.jsx
  src/components/organism/CardEditModal/HashTagsInputs.jsx
  src/components/organism/ChattingCardModal/ChattingCardModal.jsx
  src/components/organism/ChattingCardModal/ChattingCardModal.stories.jsx
  src/components/organism/ChattingCardModal/Comment.jsx
  src/components/organism/ChattingCardModal/CommentEditor.jsx
  src/components/organism/ChattingCardModal/CommentList.jsx
  src/components/organism/ChattingCardModal/Header.jsx
  src/components/organism/Modals/Modals.jsx
  src/components/organism/WaffleCard/WaffleCard.jsx
  src/contexts/user/UserProvider.jsx
  src/hooks/index.jsx
  src/hooks/useAuthUser.jsx
  src/pages/HomePage/index.jsx
  src/pages/MyPage/index.jsx
  src/pages/SignUpPage/index.jsx
  src/utils/index.jsx
  src/validators/index.jsx
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#17 [WC-37] refactor: 유저 전역 상태를 Recoil로 대체
  .storybook/main.js
  craco.config.js
  package.json
  src/App.jsx
  src/components/molecule/Spinner/Spinner.jsx
  src/components/organism/CardsContainer/CardsContainer.jsx
  src/components/organism/ChattingCardModal/ChattingCardModal.jsx
  src/components/organism/Header/Header.jsx
  src/components/organism/WaffleCard/WaffleCard.jsx
  src/constants/index.js
  src/contexts/index.jsx
  src/contexts/user/UserProvider.jsx
  src/hooks/index.jsx
  src/hooks/useUser.jsx
  src/pages/HomePage/index.jsx
  src/pages/LoginPage/index.jsx
  src/pages/MyPage/index.jsx
  src/pages/SignUpPage/index.jsx
  src/recoil/index.js
  src/recoil/user.js
  src/routes/PrivateRoute.jsx
  src/routes/PublicRoute.jsx
  yarn.lock
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#18 [WC-28] feat: GuidePage구현 및 images폴더 생성
  craco.config.js
  src/components/index.js
  src/components/organism/GuideSlider/GuideSlider.jsx
  src/components/organism/GuideSlider/GuideSlider.stories.jsx
  src/components/organism/GuideSlider/Slide.jsx
  src/components/organism/Header/Header.jsx
  src/constants/index.js
  src/images/guide/chatting.png
  src/images/guide/clickMyCardTab.png
  src/images/guide/createCard.png
  src/images/guide/viewLikeCards.png
  src/images/guide/viewTotalCards.png
  src/images/index.js
  src/images/logo.png
  src/pages/GuidePage/index.jsx
  src/pages/index.jsx
  src/routes/Router.jsx
Labels: 🧸 Feature, 🐢 리뷰 요청

#19 [WC-44] feat: 와플 카드 전역상태 관리 및 성능 개선
  src/App.jsx
  src/apis/request.js
  src/components/index.js
  src/components/molecule/LikeToggle/LikeToggle.jsx
  src/components/organism/ChattingCardModal/ChattingCardModal.jsx
  src/components/organism/ChattingCardModal/Comment.jsx
  src/components/organism/WaffleCard/WaffleCard.jsx
  src/components/organism/WaffleCardsList/CardsContainer.stories.jsx
  src/components/organism/WaffleCardsList/LoginGuide.jsx
  src/components/organism/WaffleCardsList/NoCardGuide.jsx
  src/components/organism/WaffleCardsList/WaffleCardsList.jsx
  src/contexts/index.jsx
  src/contexts/waffleCards/waffleCardsProvider.jsx
  src/hooks/index.jsx
  src/pages/HomePage/index.jsx
  src/pages/MyPage/index.jsx
  src/recoil/index.js
  src/recoil/user.js
  src/recoil/waffleCard.js
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#20 [WC-45] refactor: 와플카드리스트 useIsOverflow 훅 적용
  src/components/index.js
  src/components/molecule/LoginGuide/LoginGuide.jsx
  src/components/molecule/NoCardGuide/NoCardGuide.jsx
  src/components/organism/WaffleCardsList/WaffleCardsList.jsx
  src/components/organism/WaffleCardsList/WaffleCardsList.stories.jsx
  src/hooks/useIsOverflow.jsx
  src/pages/HomePage/index.jsx
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#22 [WC-46] refactor: atom 컴포넌트 타입스크립트로 전환
  .eslintrc
  src/components/atom/BackButton/BackButton.jsx
  src/components/atom/BackButton/BackButton.style.tsx
  src/components/atom/BackButton/BackButton.tsx
  src/components/atom/Button/Button.tsx
  src/components/atom/Input/Input.tsx
  src/components/atom/Portal/Portal.tsx
  src/components/atom/Spacer/Spacer.jsx
  src/components/atom/Spacer/Spacer.stories.jsx
  src/components/index.ts
  src/components/molecule/Spinner/Spinner.tsx
  src/components/organism/WaffleCardsList/WaffleCardsList.jsx
  src/constants/index.ts
  src/contexts/index.ts
  src/hooks/index.ts
  src/hooks/useHover.stories.jsx
  src/images/index.ts
  src/index.tsx
  src/pages/index.ts
  src/recoil/index.ts
  src/styles/index.ts
  src/styles/mixin.ts
  src/validators/index.jsx
  src/validators/index.ts
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#23 [WC-49] refactor: Header리팩토링 및 text, Header ts적용
  src/components/atom/Text/Text.tsx
  src/components/organism/Header/Header.tsx
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#24 [WC-47] refactor: molecule 컴포넌트 타입스크립트로 전환
  .eslintrc
  src/components/atom/BackButton/BackButton.stories.jsx
  src/components/index.ts
  src/components/molecule/Card/Card.jsx
  src/components/molecule/Card/Card.stories.jsx
  src/components/molecule/EditBox/EditBox.jsx
  src/components/molecule/EditBox/EditBox.style.ts
  src/components/molecule/EditBox/EditBox.tsx
  src/components/molecule/LikeToggle/LikeToggle.tsx
  src/components/molecule/Modal/Modal.tsx
  src/components/organism/WaffleCard/EmptyCard.style.ts
  src/components/organism/WaffleCard/EmptyCard.tsx
  src/components/organism/WaffleCard/WaffleCard.jsx
  src/components/organism/WaffleCard/WaffleCard.style.ts
  src/components/organism/WaffleCard/WaffleCard.tsx
  src/components/organism/WaffleCardsList/WaffleCardsList.jsx
  src/hooks/useHover.tsx
  src/types/index.ts
  src/types/user.ts
  src/types/waffleCard.ts
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#25 [WC-48] refactor: api모듈 recoil 타입스크립트로 전환
  src/apis/auth.js
  src/apis/auth.ts
  src/apis/comment.ts
  src/apis/index.ts
  src/apis/like.ts
  src/apis/request.ts
  src/apis/waffleCard.js
  src/apis/waffleCard.ts
  src/components/organism/WaffleCard/WaffleCard.tsx
  src/recoils/user.ts
  src/recoils/waffleCard.js
  src/types/waffleCard.ts
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#26 [WC-52] refactor: moleCule컴포넌트 ts전환
  src/components/atom/Text/Text.stories.tsx
  src/components/atom/Text/Text.tsx
  src/components/atom/Text/Text.type.ts
  src/components/molecule/NoCardGuide/NoCardGuide.stories.tsx
  src/components/molecule/NoCardGuide/NoCardGuide.tsx
  src/components/molecule/ScrollGuide/ScrollGuide.stories.tsx
  src/components/molecule/ScrollGuide/ScrollGuide.tsx
  src/components/molecule/Tab/Tab.stories.tsx
  src/components/molecule/Tab/Tab.tsx
  src/components/molecule/Tab/TabItem.tsx
  src/hooks/useToggle.tsx
  src/images/index.ts
  src/images/scrollGuideArrow.png
  src/pages/HomePage/index.jsx
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청

#29 [WC-55] refactor: hook, page 일부 ts전환
  src/hooks/useClickAway.tsx
  src/hooks/useSessionStorage.tsx
  src/pages/GuidePage/GuidePage.stories.tsx
  src/pages/GuidePage/index.tsx
  src/pages/LoginPage/LoginPage.stories.tsx
  src/pages/LoginPage/index.tsx
  src/pages/SignUpPage/SignUpPage.stories.tsx
  src/pages/SignUpPage/index.tsx
Labels: 🛠 Refactor, 🐰 빠른 리뷰 요청
